---
- name: Determine latest GitHub release
  when: not ansible_check_mode
  run_once: true
  delegate_to: localhost
  become: false
  register: _github_release
  retries: 5
  until: _github_release.status == 200

  ansible.builtin.uri:
    url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
    body_format: json

- name: Set node_exporter_version fact
  ansible.builtin.set_fact:
    node_exporter_version: "{{ _github_release.json.tag_name | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"

- name: Set node_exporter_download_url fact
  ansible.builtin.set_fact:
    node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz" # noqa: yaml[line-length]
