---
- name: Reload systemd units
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart node_exporter socket
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.systemd:
    name: node_exporter.socket
    state: restarted

- name: Restart node_exporter service
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.systemd:
    name: node_exporter.service
    state: restarted
